# https://docs.docker.com/compose/compose-file/

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-01-20T14-49-07Z
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always

  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.5.0@sha256:7f776bbb5457db7f58951c11e3aa881f0167675a78459d7a7f2cd5e42d181fa5
    container_name: mealie
    restart: always